### ISSUE TITLE
Android: search breaks when query includes a space

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#868] opened 2016-01-27 23:38 UTC
Searching for anything with a space in it causes the search function to spin forever.

**Comment by samuelclay** [comment] 2016-01-27 23:40
Also, once I hit a "null" bug, I can't continue to search.

**Comment by samuelclay** [comment] 2016-01-27 23:40
Actually, it's not a null stories bug at all. It's searching for anything with a space in it.

**Comment by dosiecki** [comment] 2016-01-28 00:01
Hmm, looks like our HTTP lib isn't escaping out queries quite right.  Let me forcibly encode these and see if it helps.

**Comment by dosiecki** [comment] 2016-01-28 00:06
> Also, once I hit a "null" bug, I can't continue to search.

I'm not certain what a "null bug" is. Can you give detailed steps to reproduce this?

**Comment by dosiecki** [comment] 2016-01-28 00:12
Fixed the issue with special chars.

What should the exact wording of the custom zero-stories message be?  Are there any other circumstances in the app where a custom zero-stories message should be used?

**Comment by samuelclay** [comment] 2016-01-28 19:29
Nah, don't worry about the custom message. No stories works just fine. Thanks for fixing the space bug! I'm going to release it as 7.0.1 immediately so I can blog it.

**Comment by samuelclay** [comment] 2016-01-28 19:30
(immediately as in as soon as I get the PR for the fix).

**Comment by dosiecki** [comment] 2016-01-29 12:33
Fixed in #869

**Closed by dosiecki** 2016-01-29 12:33 UTC
Labels: android, android-story-detail, critical
