### ISSUE TITLE
Android: Black Story Background on Light Theme

### ISSUE THREAD

**Issue by dosiecki** [samuelclay/NewsBlur#1179] opened 2019-03-17 06:40 UTC
On some devices, story bodies rendering in WebView widget suddenly have a black background regardless of theme.  No changes to our app.

Reported by multiple users on Android versions:
- 9 (PQ2A.190305.002) [x3]
- Q (QPP1.190205.018.B4)
- 8.0.0 (R16NW.G930FXXS4ESB2)
- 9 (PKQ1.180917.001.V10.0.5.0.PDHMIXM)
- 8.1.0 (OPW28.46-18)
-  8.1.0 (OPM7.181205.001)

Appears to be related to an update to the Chrome WebView component pushed by GOOG.  (corresponding to Chrome v73, possibly)

Possible workarounds:
- users can uninstall / revert update to Chrome WebView
- NewsBlur server could wrap story bodies in CSS styling to force lighter default background

Permanant fix is probably just a tweak to the in-app CSS override file, but is blocked by #1178.

**Comment by t-8ch** [comment] 2019-03-29 17:17
For me it also works to switch the theme to dark or black because it changes the fontcolor to white, making it readable again.

**Comment by firesock** [comment] 2019-04-01 20:29
Unsure if this is exactly the same issue, but a similar looking bug reported against Chrome WebView: https://bugs.chromium.org/p/chromium/issues/detail?id=943556

**Comment by dosiecki** [comment] 2019-04-05 07:04
Just chiming in to confirm that Chromium Issue 943556 (and a few other ones that have been reported against Android and/or Chromium) have confirmed that this probably wasn't expected behaviour on the Chrome project's part.  There have also been a few reports coming in that there is a fixed version of the Chrome WebView being tested or deployed.

In the meantime, some early work on #1178 has got us to the point where in theory we could push a beta fix, *but*, said upgrade would almost totally break background sync on newer devices.  Working to resolve that potential trade-off.

**Comment by firesock** [comment] 2019-04-06 08:49
Tested by changing my WebView implementation to one provided by Chrome Canary 75.0.3756.0 and I'm still seeing the problem.

**Comment by samuelclay** [comment] 2019-04-10 00:44
Hey Daniel, how close are we to shipping this to the beta channel?

**Comment by dosiecki** [comment] 2019-04-14 19:55
As expected, the prerequisite catch-up work to cut a new version (#1178) is involving quite a few changes.  I'll document progress in that ticket.  Due to some personal matters, I haven't been able to make enough progress there to predict how close we are to being ready to cut any kind of build.  Will update as things progress.

**Comment by t-8ch** [comment] 2019-04-30 09:02
Seems to be fixed by "Android System WebView 74.0.3729.112"

**Comment by cuviper** [comment] 2019-04-30 16:19
> Seems to be fixed by "Android System WebView 74.0.3729.112"

I have this version on my Samsung Galaxy S9, but the problem persists.

**Comment by gelzi** [comment] 2019-04-30 16:38
The problem also persists on Google pixel 3 with  that version.

**Comment by t-8ch** [comment] 2019-04-30 19:44
Not sure what I saw, but I double-checked it; and indeed the problem persists...

**Comment by samuelclay** [comment] 2019-04-30 20:42
Oh boo, I wish that wasn't the case. I'm going to post a call for an Android developer tomorrow when I have time to review applicants. If anybody in this thread knows of an Android developer who wants to work on NewsBlur on an ongoing basis please let me know before I post the call tomorrow.

Pay is $2k/month and hours are whatever you want. I don't care how much you do, only that the work gets done and people are happy.

**Comment by caleb-allen** [comment] 2019-05-06 22:35
I've done some digging, I believe the source of the issue is from the upcoming Dark Mode, It was added to Chromium [here](https://chromium.googlesource.com/chromium/src/+/0368e4698f8b336059be7bb4c56f53158fbfae74%5E%21/#F13)

That change also appears in 74.0.3729.112.

Interestingly, I'm able to get normal behavior after bouncing between chrome and NewsBlur, with a Chrome Remote Debugger session from my workstation. Restarting the device resurfaces the issue.

**Comment by caleb-allen** [comment] 2019-05-06 22:38
For a quick fix for users, give this a try.

Go to `chrome://flags` and set the flag `#enable-android-web-contents-dark-mode` to `Disabled`.

In the meantime, I'm investigating exactly what heuristic Google is using to determine whether Dark Mode is enabled in chromium. By default it is set to `FORCE_DARK_AUTO`, but that is not accessible until Android Q: https://developer.android.com/reference/android/webkit/WebSettings.html#setForceDarkMode(int)

**Comment by cuviper** [comment] 2019-05-06 23:15
> Go to `chrome://flags` in chrome and set the flag `#enable-android-web-contents-dark-mode` to `Disabled`.

I also had to swipe NewsBlur closed in the recent app list, so the setting was picked up when it started fresh, but this worked, thanks!

**Closed** 2019-05-10 01:48 UTC
Labels: android, android-story-detail, critical

**Comment by t-8ch** [comment] 2019-05-17 14:39
Another update of the "Android System WebView" to 74.0.3279.157 it seems to actually work again, even after a phone restart.
(Newsblur App at 8.0.0)

**Comment by caleb-allen** [comment] 2019-05-18 00:09
My goodness, seems like the goalposts keep moving.

https://chromium.googlesource.com/chromium/src.git/+/dfcaff8955227305cb094c0c3e6b3d0a595ce30e%5E%21/#F0

This progressive rollout of dark mode has left us users of WebViews to scramble, it seems

**Comment by caleb-allen** [comment] 2019-05-18 02:13
@samuelclay I'm getting that issue again like you mentioned, I believe another chrome update is doing it in certain cases. The dark mode code seems to be changing quickly.

I'm unable to make the fix again using the css media query from before, nor with the elements specified from the spec.

https://bugs.chromium.org/p/chromium/issues/detail?id=925935

It appears the css to override this has not been implemented yet:
https://bugs.chromium.org/p/chromium/issues/detail?id=925935

It *also* appears that the `#enable-android-web-contents-dark-mode` chrome flag no longer fixes the issue.

I'm somewhat at a loss, I've filed a bug with the chrome team. I think there is something being tweaked in chrome that wasn't meant to be user facing at this point, meaning our options might be limited to fix it.

https://bugs.chromium.org/p/chromium/issues/detail?id=964594

**Comment by caleb-allen** [comment] 2019-05-20 19:31
Looks like the chromium issue is getting some attention from Googlers which is great to see.

**Comment by samuelclay** [comment] 2019-05-28 13:48
Can we just arbitrarily add a "background: white" when the light theme is enabled?

**Comment by caleb-allen** [comment] 2019-05-28 21:13
That's what the previous patch was :\

This is what is most confusing to me: the "dark mode" is overriding our UI, including those CSS properties. I'm fiddling to see if I can reliably get it to not allow the override.
