### ISSUE TITLE
Web: Search loses keyboard focus before query is entirely typed out

### ISSUE THREAD

**Issue by Splike** [samuelclay/NewsBlur#1276] opened 2020-01-14 03:09 UTC
I often find that the search feature will start the search before I've finished typing, making me accidentally press all sorts of keybound shortcuts.

An option to only start searching when I've hit the enter button, would fix this and make me want to use search more often.

**Comment by samuelclay** [comment] 2020-05-21 21:34
The real problem here is that the search is causing your keyboard to lose focus.

**Comment by samuelclay** [comment] 2020-05-21 21:35
What browser are you using?

**Comment by samuelclay** [comment] 2020-06-09 01:16
Dupe of #1009. Will fix soon!

**Closed by samuelclay** 2020-06-09 01:16 UTC
Labels: critical, web
