### ISSUE TITLE
iOS: Back button double overlaid on iPhone

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1497] opened 2021-06-07 16:14 UTC
This screenshot came from TestFlight feedback. No idea how they got it there but some code path may be missing an iPhone check. 

![original](https://user-images.githubusercontent.com/44229/121053804-ba997c00-c789-11eb-9daa-1f99a7ab3763.jpg)

**Comment by Dejal** [comment] 2022-05-27 02:57
I can't reproduce this, or determine a way it could occur (obviously it did, but no idea how). Maybe it was some edge case that has already been fixed. So I'll close it; feel free to re-open if anyone else reports it.

**Closed by Dejal** 2022-05-27 02:57 UTC
Labels: medium, iOS
