### ISSUE TITLE
iOS: Crash on opening notifications

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1455] opened 2021-04-26 14:42 UTC
I just moved to the TestFlight build and notifications work again. So when I tapped on a couple I had some issues.

The first notification re-opened NewsBlur, which was on a different feed and story. So the app backed out to the feed list and then crashed.

The second notification opened NB and simply didn't open the feed.

I recommend installing the TestFlight build and turning on some chatty feeds so you have plenty of notifications in your notification history to test with. I could fix notifications on Xcode builds by using a different certificate. In fact, I thought I did fix it by setting a user profile flag that uses the other certificate, but it seems to not be working.

**Comment by Dejal** [comment] 2021-05-09 04:01
I did that, and didn't get any crashes. Most of the time it correctly displayed the story, but once only went to the feed detail and gave up, and another time gave up at the feeds list.

I've burned through all of my notification queue, so I'll try again another time once I've accumulated more.

**Comment by samuelclay** [comment] 2021-05-13 23:10
It's like every notification for me. I can't get any notifications to load at all, in fact. Often there's a crash after the feed list loads but before the feed is opened. But just as often it sits at the feed list. Every fifth time it opens the story, but the feed is (null).

**Comment by Dejal** [comment] 2021-05-21 22:15
Issues like this are frustrating, where I don't experience the problem 99% of the time... and the few times I have experienced something, the debugger doesn't stop in a way that helps diagnose it.

I've committed a couple of tweaks that might help, and will keep trying, but I've been through about 50 notifications last night and as many again just now, with a couple of issues last night, and zero just now — every time it correctly loads the feed and story.

It's a lot slower with the debugger attached, which maybe could contribute to it being more reliable... so I tried running without Xcode, and it still worked. Frustrating.

Perhaps you could try running from Xcode and see if you can get it to crash, and provide the backtrace of where. I might be able to add some logic to avoid that, even without reproing it myself.

**Comment by samuelclay** [comment] 2021-05-27 20:59
I noticed that stories are never found when the app is starting cold. Try force quitting it and then opening a notification.

**Comment by samuelclay** [comment] 2021-05-27 21:00
Also, if you want a high volume feed for testing notifications but don't want something obnoxious, I've found Axios to be a neutral and prolific publisher. Lots of news and becuase its RSS, it never feels goosed, unlike notifications from newspapers.

**Comment by samuelclay** [comment] 2021-06-02 20:17
So I'm not getting a crash but when I opened a notification on today's build, I caught this exception (and nothing happened):

```
2021-06-02 16:15:41.998678-0400 NewsBlur[17651:2396639] ⚠️ showing story pages: split view controller: <NewsBlur.SplitViewController: 0x13bd0b1b0> split nav: (null); split controllers: (
    "<UINavigationController: 0x13c019000>"
); detail controller: <NewsBlur.DetailViewController: 0x13bd11020>; detail nav: <UINavigationController: 0x13c85a600>; detail nav controllers: (
    "<NewsBlur.DetailViewController: 0x13bd11020>"
)
2021-06-02 16:15:41.998792-0400 NewsBlur[17651:2396639] ...shown
2021-06-02 16:15:42.284247-0400 NewsBlur[17651:2396639] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2021-06-02 16:15:42.284295-0400 NewsBlur[17651:2396639] WF: _WebFilterIsActive returning: NO
2021-06-02 16:15:42.286220-0400 NewsBlur[17651:2396639] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2021-06-02 16:15:42.286264-0400 NewsBlur[17651:2396639] WF: _WebFilterIsActive returning: NO
2021-06-02 16:15:42.287033-0400 NewsBlur[17651:2396639] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2021-06-02 16:15:42.287068-0400 NewsBlur[17651:2396639] WF: _WebFilterIsActive returning: NO
2021-06-02 16:15:42.288587-0400 NewsBlur[17651:2396639] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2021-06-02 16:15:42.288628-0400 NewsBlur[17651:2396639] WF: _WebFilterIsActive returning: NO
2021-06-02 16:15:42.291232-0400 NewsBlur[17651:2396639]  ---> Loading feed url: https://beta.newsblur.com/reader/feed/7500936/?include_hidden=true&page=2&order=newest&read_filter=all
2021-06-02 16:15:42.363357-0400 NewsBlur[17651:2396639] showStoryImage for row 3 of 6
2021-06-02 16:15:42.369554-0400 NewsBlur[17651:2396639] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2021-06-02 16:15:42.369613-0400 NewsBlur[17651:2396639] WF: _WebFilterIsActive returning: NO
2021-06-02 16:15:42.385376-0400 NewsBlur[17651:2396639] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2021-06-02 16:15:42.385424-0400 NewsBlur[17651:2396639] WF: _WebFilterIsActive returning: NO
2021-06-02 16:15:42.436795-0400 NewsBlur[17651:2398129] [connection] nw_endpoint_handler_set_adaptive_read_handler [C412.1 167.99.229.118:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for read_timeout failed
2021-06-02 16:15:42.436843-0400 NewsBlur[17651:2398129] [connection] nw_endpoint_handler_set_adaptive_write_handler [C412.1 167.99.229.118:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for write_timeout failed
2021-06-02 16:15:42.439175-0400 NewsBlur[17651:2398129] [connection] nw_endpoint_handler_set_adaptive_read_handler [C413.1 167.99.229.118:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for read_timeout failed
2021-06-02 16:15:42.439217-0400 NewsBlur[17651:2398129] [connection] nw_endpoint_handler_set_adaptive_write_handler [C413.1 167.99.229.118:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for write_timeout failed
2021-06-02 16:15:42.467983-0400 NewsBlur[17651:2396639] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Cannot display a nested UINavigationController with zero viewControllers: <UINavigationController: 0x13c82c800>'
*** First throw call stack:
(0x19b5dd754 0x1b00a47a8 0x19b4d27e0 0x19d7e4708 0x19d7e52f4 0x19d7e4f88 0x19d8d0df4 0x19d8cd3a8 0x19d8cd084 0x19d8e35f8 0x19e500b80 0x19e4d31f8 0x19e4d375c 0x19e4d38c4 0x19e9a98ec 0x10535dde0 0x10536e0a8 0x19b557398 0x19b551270 0x19b550360 0x1b2b8e734 0x19dfcb584 0x19dfd0df4 0x104d4b09c 0x19b20ccf8)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Cannot display a nested UINavigationController with zero viewControllers: <UINavigationController: 0x13c82c800>'
terminating with uncaught exception of type NSException
```

**Comment by samuelclay** [comment] 2021-06-02 20:17
This was on my iPhone SE

**Comment by Dejal** [comment] 2021-06-05 04:50
I spent some more time on this, without any success reproducing it, or narrowing down where it failing, though it seems to be when showing a split column.

So I added more debug logging to try to trace the issue you found. If you experience an exception like that again, please include the logging. 

If you can provide the dSYM file from the TestFlight build archive, that might help too.

**Comment by samuelclay** [comment] 2021-06-07 17:46
I'm really noticing the problem on my iPhone, so split screen shouldn't be a part of it. I do notice that when there's no feeds loaded (on a cold start for instance, which is basically when I don't use the app for an hour), the notification invariably fails to load the story, even when the feeds come in.

**Comment by Dejal** [comment] 2021-07-05 22:52
Alrighty, after much more testing, tracing logic, and managing to reproduce an issue on my iPhone, I think (hope) I've finally fixed this. I'm going to optimistically close this, but you can of course re-open with more info if you still experience an issue with notifications.

**Closed by Dejal** 2021-07-05 22:52 UTC
Labels: critical, iOS
