### ISSUE TITLE
Android: Add show hidden stories button

### ISSUE THREAD

**Issue by Philipp91** [samuelclay/NewsBlur#1786] opened 2023-02-27 20:52 UTC
On Web, there's a setting at the top right: "Show/Hide hidden stories". The equivalent doesn't seem to exist in the Android app, which just always displays all hidden stories -- which defeats the point of having "hidden" stories in the first place.

So my feature request would be to add such a filter to the Android app as well.

**Comment by sictiru** [comment] 2023-03-13 00:12
Could you share a screen shot of the option on web? I'm having some trouble locating it.

@samuelclay All the story related API calls send `include_hidden=true` with the exception of the widget stories. Is that intentional? I don't remember why the widget doesn't include hidden stories.

**Comment by samuelclay** [comment] 2023-03-13 13:51
Yep, if you include_stories=true, you'll get a bunch of negative/red stories, so you'll need to page a bit more intentionally, since you could easily get 6 stories of reds in a row (6 stories per page). I use Hacker News to test this scenario, where I thumbs down the whole feed but thumbs up "Ask HN", but gives me a bunch of red stories occasionally populated by green.

**Comment by samuelclay** [comment] 2023-04-09 18:58
This is a terrific feature to build since we already have the data, it's just a button that allows us to toggle between CSS classes that show/hide the <del> and <ins>

**Comment by sictiru** [comment] 2023-04-09 22:52
Thanks for clarifying the expected outcome. I need to revert some of the changes I already made and add the toggle button for CSS.

**Comment by sictiru** [comment] 2023-04-09 23:39
@samuelclay Isn't that the existing `Show Story Changes` button?

**Comment by samuelclay** [comment] 2023-04-09 23:52
Sorry I flubbed that. You're right, this is the story titles view. We need a Show Hidden Stories button in that view if there are negatively scored articles.

**Comment by sictiru** [comment] 2023-04-10 01:51
@Philipp91 Are you using the `All` tab on the main page or `Unread` when you're looking to toggling these hidden stories? In the `All` tab the hidden stories are currently always shown but in the `Unread` tab these are hidden.

**Comment by sictiru** [comment] 2023-10-30 19:37
Closing ticket. Feel free to reopen if the issue is still valid.

**Closed by sictiru** 2023-10-30 19:37 UTC
Labels: high, android, android-story-list, blocked

**Comment by Philipp91** [comment] 2023-10-30 19:52
> @Philipp91 Are you using the `All` tab on the main page or `Unread` when you're looking to toggling these hidden stories? In the `All` tab the hidden stories are currently always shown but in the `Unread` tab these are hidden.

Sorry, I hadn't received notifications for this question.

I was using the "All" tab, but with the "Read story filter" -> "Unread only" selected. I wasn't aware that there was the other "Unread" tab.  I've just tried the "Unread" tab and it seems to be doing exactly what I want. Great, thank you!

For the UX of other users: Why is there the filter in the menu _and_ the tab? Aren't these two features that offer the same functionality and only differ in whether they show hidden stories or not (a side effect that can't be inferred from their name)? Actually, I may be misunderstand that "Unread tab" entirely: When I use it, but disable the "Unread only" filter in the menu, then even when I'm on the "Unread" tab it displays read stories to me too. Does this only filter the folders shown on the main screen (and then magically also influence whether hidden stories are shown in the stories list after clicking one of those folders)?

And an even more tangential side note: Those tabs don't feel like tabs at all to me. Nothing in the remainder of the screen changes when I click "All" or "Screen", so I'd characterize them as "filter buttons in the bottom bar".

**Comment by Philipp91** [comment] 2023-12-01 21:58
I found a bug with the "Unread" tab: I've been using it for a while now, and as intended it doesn't show hidden stories. However, it appears to load them still. When I scroll through, I mark all the regular (non-hidden) stories as read. So, since this is the "Unread" tab, those won't be shown anymore once I reopen the same folder. And since I use "Oldest first" sorting, there comes a time when there are dozens of unread, hidden stories at the front of the list that _would_ be visible in the "All" tab but aren't in the "Unread" tab. This makes NewsBlur choke:

Upon loading such a folder on web, you can see it flickering a couple of times on an empty list, before finally the real unread, non-hidden stories in that folder become visible. On Android, it only shows today's stories at first, but while I'm scrolling down, it pushes some oder unread stories to the top of the list, messing up the list order and breaking the "mark read on scroll" feature. I'm quite sure this is caused by the many hidden unread stories at the "front" of the list, and more specifically, when their number exceeds the pagination size of the load-from-server mechanism.

My proposal would be to also mark hidden stories as read when scrolling past them, even if they're not visible. Or, alternatively, to implement the load-from-server mechanism for the "Unread" tab separately, so that it returns a full page of non-hidden stories from the server, so that the loaded page can never become empty by client-side filtering of hidden stories.

**Comment by samuelclay** [comment] 2023-12-04 14:28
Post a video if you can!
