### ISSUE TITLE
iOS: widget is slow to reload

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1607] opened 2022-01-29 17:08 UTC
I think we should separate out performance from styling. In fact, I think this is responsible for this bug I saw today:

![image](https://user-images.githubusercontent.com/44229/151670205-cdc893d8-b1f8-44f2-b158-16eb485a5e04.png)

**Comment by Dejal** [comment] 2022-02-01 06:20
I'm doing some analysis to see if I can find bottlenecks, and use that to improve the loading performance. A more complex solution might be to use data loaded by the main app, perhaps if sufficiently recent, but there are some issues with that. I'll see what I can come up with.

That message should mean what it says; no eligible stories for the sites. I don't think it'd appear due to loading time.

**Comment by Dejal** [comment] 2022-02-01 23:56
The two time-consuming parts are (unsurprisingly) fetching the stories, and fetching the images (feed and story). So a solution could be (as you suggested via email) to move that to server side, with a single endpoint call to get JSON data with the relevant number of stories with their images.

**Parameters:**

- Number of stories to fetch (currently 3 for small, 6 for large)
- The user token
- An array of feed IDs for which to fetch stories.
- An array of feed IDs that have already been fetched, so don't need to include favicon images for them.
- An array of story hashes that have already been fetched, so don’t need to include thumbnail images for them.

**Response:**

A JSON object (dictionary) containing:

- An array of feed info:
  - `id`
  - `feed_title`
  - `favicon_color`
  - `favicon_fade`
  - `favicon_image`
- An array of story info:
  - `story_hash`
  - `story_feed_id`
  - `short_parsed_date`
  - `story_title`
  - `thumbnail_image`: only included if not in the parameter array
 
Can omit feed info for feeds specified in the parameter of already fetched feeds.

Alternatively could return a single array of stories, with the feed info embedded, if only including the feed image once, if needed.

Or could simplify by skipping those parameters, and always return all of the images; should be negligible extra server or data transfer time.

Also the story images can be pre-scaled to 192x192 pixels, which will reduce the time to fetch them.

What do you think?

**Comment by samuelclay** [comment] 2022-02-02 00:52
Nice job, I'll build that endpoint tomorrow. As for story images, you can use the new story image proxy, which will happily resize images based on the url, which is provided per-thumbnails in the `secure_image_thumbnails` dictionary per story.

**Comment by Dejal** [comment] 2022-02-02 00:56
I do fetch images from `secure_image_thumbnails`, though may not provide a resizing parameter? Though doing multiple requests has a cost, too; combining them into one would be faster.

Here's some sample logging, with annotations:

```
16:37:17.720963-0800	getTimeline: loadCachedStories took 0.050120 seconds (total 0.050120 seconds) 🚨🚨
```

Loading the cached stories is fast.

```
16:37:22.698584-0800	/reader/river_stories data: 56892 bytes
16:37:22.704185-0800	getTimeline: cache.load() took 4.983235 seconds (total 5.033355 seconds) 🚨🚨🚨🚨
```

Fetching the stories from the server takes 56 KB and five seconds (on my admittedly not very fast cellular connection).

```
16:37:22.704469-0800	getTimeline: making timeline took 0.000302 seconds (total 5.033657 seconds)
```

Making the widget timeline records is very fast.

```
16:37:23.733661-0800	/reader/favicons data: 73 bytes
16:37:25.703516-0800	/192,sc,s7TKN8EGVgRYuU4tUwy8rgLEkEe7P83bb8bH361Po_JM=/https://cdn.cnn.com/cnnnext/dam/assets/220201170415-clarissa-ward-ukraine-front-line-vertical-large-gallery.jpg data: 18082 bytes
16:37:26.009445-0800	/192,sc,s7x0JcoxR9lCg7RvvjratHb7J3WZnmA0iYD4QUCjdvvw=/https://www.macworld.com/wp-content/uploads/2022/02/imessage-android-expressions-1.jpg data: 10906 bytes
16:37:26.064815-0800	/192,sc,sshCx-Fld1anr7lBIkLqbsRQq2zJhyUvPSX0Cc0XnTf8=/https://cdn.cnn.com/cnnnext/dam/assets/220201174244-rep-chip-roy-justin-trudeau-split-vertical-large-gallery.jpg data: 512 bytes
16:37:26.938811-0800	/192,sc,s7x0JcoxR9lCg7RvvjratHb7J3WZnmA0iYD4QUCjdvvw=/https://www.macworld.com/wp-content/uploads/2022/02/imessage-android-expressions-1.jpg data: 6963 bytes
16:37:26.938962-0800	/192,sc,sshCx-Fld1anr7lBIkLqbsRQq2zJhyUvPSX0Cc0XnTf8=/https://cdn.cnn.com/cnnnext/dam/assets/220201174244-rep-chip-roy-justin-trudeau-split-vertical-large-gallery.jpg data: 3282 bytes
16:37:27.603821-0800	/192,sc,sshCx-Fld1anr7lBIkLqbsRQq2zJhyUvPSX0Cc0XnTf8=/https://cdn.cnn.com/cnnnext/dam/assets/220201174244-rep-chip-roy-justin-trudeau-split-vertical-large-gallery.jpg data: 8403 bytes
16:37:27.611802-0800	getTimeline: requesting images took 4.907317 seconds (total 9.940974 seconds) 🚨🚨🚨🚨
```

Fetching the story images is a bunch of data via several requests, taking another five seconds (paths appearing more than once indicates multiple data chunks; the images are fetched simultaneously). The widget update takes a total of 10 seconds.

Combining all of that into one request, with properly scaled images, should reduce it to only a few seconds, even on my slow connection.

**Comment by samuelclay** [comment] 2022-02-02 14:41
In the secure story image url, the `192,sc` are the scaling parameters. But what I'll do is do the fetch on the server-side (we already have the infrastructure for 3-5 second requests) and base64 encode them.

I wish I supported Python 3's async libs. This may be the time to implement the first one!

**Comment by samuelclay** [comment] 2022-02-02 20:14
Ok, here's the URL: `/reader/river_stories_widget`. Works the same as river_stories (in fact, it uses river_stories), plus it adds the `select_thumbnail_data` key to each story if it found the image in less than 3 seconds. Make sure to set `limit=6` so you only get 6 stories back. 

This uses the imageproxy which also caches images, so it'll be faster for subsequent users. The image is base64 encoded. Happy to use another encoding, but it's json so we're a bit limited.

Let's see if having a single request and centralized image fetching takes care of 90% of performance without having to dip into a more custom endpoint.

**Comment by Dejal** [comment] 2022-02-02 20:54
Thanks. Does the `limit=6` account for hidden stories too?

**Comment by Dejal** [comment] 2022-02-02 21:01
Oh, and I guess it just includes story images, not feed images? Which is probably fine, since there will be a limited number of feed favicons, they're cached, and they're small.

**Comment by samuelclay** [comment] 2022-02-02 21:09
> Does the limit=6 account for hidden stories too?

No, but you also won't receive hidden stories unless you also pass in `include_hidden=true`. So you may have to page through this to fill it up. It wouldn't be all that difficult to do on the backend. Just build some recursive footer that builds up the list until its either full or out of tries. Maybe a `replace_hidden_stories=true` flag, knowing it'll take a while.

**Comment by Dejal** [comment] 2022-02-02 21:13
No, it just requests one page. Which would be why it sometimes didn't find enough for you. So in the interest of reducing network calls, if you can fill it up on the server, that'd help.

**Comment by Dejal** [comment] 2022-02-02 22:44
I didn't see any image scaling in the server code (though perhaps I missed it?). If not, please add that too; no point in sending back full-sized images. I'll pass a `thumbnail_size` parameter for the desired size. To allow for the different display sizes and retina, I'll probably use `thumbnail_size=300`.

I'll also pass `replace_hidden_stories=true`, to fill up to the requested number of stories.

**Comment by Dejal** [comment] 2022-02-02 23:23
Better performance, sometimes; it's loading a lot more data with the stories, presumably because the images are not pre-scaled, so should be faster once you do that:

```
	15:14:33.003711-0800	getTimeline: loadCachedStories took 0.068593 seconds (total 0.068593 seconds) 🚨🚨
	15:14:35.992250-0800	/reader/river_stories_widget data: 49541 bytes
	15:14:36.112763-0800	/reader/river_stories_widget data: 8996 bytes
	15:14:36.223042-0800	/reader/river_stories_widget data: 19657 bytes
	15:14:36.418979-0800	/reader/river_stories_widget data: 21653 bytes
	15:14:36.530838-0800	/reader/river_stories_widget data: 20638 bytes
	15:14:36.681008-0800	/reader/river_stories_widget data: 20841 bytes
	15:14:36.681580-0800	/reader/river_stories_widget data: 11 bytes
	15:14:36.789336-0800	/reader/river_stories_widget data: 21323 bytes
	15:14:36.904323-0800	/reader/river_stories_widget data: 28976 bytes
	15:14:37.019175-0800	/reader/river_stories_widget data: 16307 bytes
	15:14:37.029264-0800	getTimeline: cache.load() took 4.025544 seconds (total 4.094137 seconds) 🚨🚨🚨🚨
	15:14:37.029432-0800	getTimeline: making timeline took 0.000201 seconds (total 4.094338 seconds)
	15:14:37.886876-0800	/reader/favicons data: 73 bytes
	15:14:37.888847-0800	getTimeline: requesting images took 0.859388 seconds (total 4.953726 seconds) 🚨🚨🚨
```

Also, sometimes the thumbnail image is some sort of placeholder; the server should return no image rather than this:

<img width="342" alt="Placeholder" src="https://user-images.githubusercontent.com/1318849/152253950-e4a9629f-27cb-4554-a095-3923ee90e065.png">

**Comment by samuelclay** [comment] 2022-02-03 12:48
Those are pre-scaled images, at 192px. I think that's why they're all around 20k. Compare this image that has a lot of white background:

(9.8k, 192px) https://imageproxy.newsblur.com/192,sc,sh4rvrCkwJtXWlh2n3jdgvnxX6GSI7P1jG-VsnD95GNM=/https://techcrunch.com/wp-content/uploads/2022/02/Amira-Yahyaoui_.jpg

(1.5MB, original) https://imageproxy.newsblur.com/sc,sh4rvrCkwJtXWlh2n3jdgvnxX6GSI7P1jG-VsnD95GNM=/https://techcrunch.com/wp-content/uploads/2022/02/Amira-Yahyaoui_.jpg

 As for choosing a better image, the setup I have doesn't actually know the original dimensions, so it will naively scale up images. Thinking about ways of addressing that, but it's a known issue.

**Comment by Dejal** [comment] 2022-02-17 00:14
We can probably close this now, unless you want to try any further tweaks?

**Comment by samuelclay** [comment] 2022-02-18 18:14
After switching to the staging server, I can't get it to load. Rebooted my phone and still showing this load screen. I'm watching the staging logs and the widget river endpoint is never called. And when I tapped on the widget, no sites were checked. Makes sense, given I changed servers, but we should probably handle this by deleting things or something.

I committed the staging to the testflight branch, but it's the PROD_DEBUG flag.

**Comment by samuelclay** [comment] 2022-02-22 14:51
Should be https

**Comment by samuelclay** [comment] 2022-03-01 19:32
I'm seeing this still with the main www as well. 

https://user-images.githubusercontent.com/44229/156235718-218ae1f7-5212-4d63-96cc-1d44cb3f85ea.MP4

**Comment by Dejal** [comment] 2022-03-08 04:56
I sometimes get that too.

The cause is the `/reader/river_stories_widget/` request is getting the error:

```
Error Domain=NSURLErrorDomain Code=-999 "cancelled"
```

This is with this request, with lots of feeds:

```
https://www.newsblur.com/reader/river_stories_widget/?include_hidden=false&replace_hidden_stories=true&thumbnail_size=192&page=1&infrequent=false&order=newest&read_filter=unread&limit=6&f=8264795&f=3581&f=8264796&f=109755&f=1003963&f=8264797&f=569&f=8337202&f=183139&f=7808652&f=7300406&f=1186180&f=2186&f=192575&f=4353&f=3233139&f=76&f=26931&f=8429586&f=1340342&f=1485973&f=5994357&f=1590355&f=6037101&f=5719953&f=7049261&f=2998&f=5168&f=1665281&f=7101685&f=6342410&f=1272495&f=3240&f=7505145&f=2308&f=6038475&f=6238772&f=1138885&f=2907440&f=6238774&f=212379&f=1010775&f=6556107&f=146&f=4153&f=3530&f=8261266&f=6476&f=38&f=644144&f=8264790&f=8264791&f=8264792&f=8264785&secret_token=2785fe5513db
```

Error 999 can be caused by doing the exact same request twice (which doesn't happen), losing the reference to the request (which also doesn't happen), or by a certificate issue on the server (which doesn't seem to be the case, since it works sometimes).

Experimentation shows that it is more likely to happen with lots of feeds, and less likely with only a few. Which suggests it could be a timeout issue, of the server taking too long.

I'll experiment some more.

**Comment by samuelclay** [comment] 2022-03-08 18:31
Oh you nailed it with that URL. It's a 500 exception and I've got the traceback in Sentry. Just deployed a fix and that url should work now.

Problem was that some images in stories are encoded as data-uri, so the backend was naively sending them to the imageproxy, which choked: https://imageproxy.newsblur.com/192,sc,sEermKyn22l4_mZxwHOr2dW9Esbadb7MZWomoqKJquj0=/data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmVyc2lvbj0iMS4xIi8+

So I set it to ignore data-uri images and it now that url is working for me. The widget is still a single grey line, but i moved back to the testflight version (which is why I think I regressed on the folder highlight bug). 

One thing that would personally help me is to hide muted feeds in the widget list. I have 900 feeds but only 400 aren't muted. And that Widget dialog is a bit wonky as it'll show up all checked off and then suddenly all the checkmarks disappear. Would be nice to show a loading indicator.

**Comment by Dejal** [comment] 2022-03-09 03:48
I'm glad you were able to spot the issue. That does seem to have fixed it.

Hiding muted feeds in the widget sites preference is a good idea.

Another concept that I've been thinking about, and might try if you don't object, is to add a new smart folder for widget sites, showing only the feeds selected in the widget prefs. And show that feed when loading from a widget. That would make finding a story much faster, since the ones shown in the widget should be right at the top.

I don't see the widget sites preference loading wonkiness; it loads immediately. I tried logging in as you, but it still loads immediately, at least in the Simulator. But hiding muted sites might help.

**Comment by samuelclay** [comment] 2022-03-10 21:06
I feel like the widget feed selection is too fine-grained. I either want a single feed or a folder, defaulting to the all folder. And I'm struggling with the widget feed list right now because the widget is now showing a "Tap to setup in newsblur" message, and sometimes the widget dialog shows all of my sites selected and sometimes deselected. 

I just released this on TestFlight and will promote to prod tomorrow if I don't hear any complaints. The widget may not work for me but we'll fix it quickly enough if others have the same issue.

**Comment by samuelclay** [comment] 2022-03-10 21:31
After playing with the Widget Site Stories folder, I'm more convinced this should only feature the option for a single feed or a folder. These can be shown in two lists, so folders are shown first. 

There's also a bug with the Widget Site Stories folder that shows all sites, including muted sites, on the feed list when go into the Widget Site Stories folder and swiping back to the feed list. 

The use case for the Widget Site Stories folder is better served by allowing multiple instances of the widget with different single feed/folder settings.

**Comment by Dejal** [comment] 2022-03-11 00:14
I agree ideally supporting multiple instances of the widget, each with their own single feed/folder settings, would be the ideal. I could work on that next week if you wanted to hold off the release for it. It will take some time, though.

Alternatively, I could rip out (or just hide) the the new Widget Site Stories smart folder, replace the Widget Sites preferences with a picker for a single folder/feed (like when moving a feed), and display that folder/feed when tapping a story in the widget. That would be much faster. (And if you reply promptly, I could probably do it tonight or tomorrow.)

Or we could go with the current implementation for now.

Let me know what you'd prefer.

**Comment by samuelclay** [comment] 2022-03-11 10:48
> Alternatively, I could rip out (or just hide) the the new Widget Site Stories smart folder, replace the Widget Sites preferences with a picker for a single folder/feed (like when moving a feed), and display that folder/feed when tapping a story in the widget. That would be much faster. (And if you reply promptly, I could probably do it tonight or tomorrow.)

Yep, let's do this for now. And we can ship multiple widget later, although that should probably be in the dejal branch and any hotfixes should go in testflight.

**Closed** 2022-03-12 04:32 UTC
Labels: critical, iOS

**Comment by samuelclay** [comment] 2022-03-12 11:10
Im still not seeing stories. The widget doesn't make any requests, so there's a hint that's somethings wrong.

**Comment by Dejal** [comment] 2022-03-12 16:04
Weird. Trying to think of possibilities... you have done a clean build, to ensure the widget is up-to-date? You have set some sites in the Widget Sites prefs? You are using the new widget, not the old Today widget?

Have you tried selecting different sites, to see if certain sites are causing it?

When running in Xcode, you could attach a debugger to the widget to see what it is doing; perhaps something in the data causing an exception, or something.

**Comment by Dejal** [comment] 2022-03-14 16:52
🎉
