### ISSUE TITLE
iOS: When app is killed in background, story and position don’t return

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1290] opened 2020-03-11 19:12 UTC
When I just logged the last bug, after returning to NewsBlur a minute later, it was killed and the wrong story was loaded. I want this feature to work flawlessly, so let’s spend a month or two tracking down the issue.

I’m on an iPad with a Smart Keyboard and in landscape orientation. I suspect the story pager recorded the wrong story for whatever reason, since I would expect the All Site Stories list to load without finding the original story, now that its state is read. Instead it found a different story. (...) It looks like it was just the first story.

**Comment by samuelclay** [comment] 2020-03-11 19:14
Since we know we’re in looking for story mode, how about loading in All Stories `unread_filter` instead of the folder/feed’s preference.

**Comment by Dejal** [comment] 2020-03-14 21:46
That's a tricky one to investigate. What is supposed to happen, and does happen in my testing, is that when the app goes in the background, the current story is temporarily marked as unread, and the feed and story IDs are saved in the state restoration info.

If the app gets killed by the system (not force quit by the user), the state restoration mechanism will kick in, re-displaying that same feed and story, and re-marking it as read.  That all works fine in my testing now.

As I recall, if the story can't be found (e.g. because it's been a while), it might select the first story in the feed, as better than nothing.

If the app is force quit, or crashes, the state is not restored.

The state restoration logic is fairly complex, so I could imagine that it could fail in some situations, but I might need more info on how to reproduce an issue. I'll continue to test it and see if I can get it to fail.

**Closed** 2020-03-25 00:07 UTC
Labels: critical, iOS
