### ISSUE TITLE
iOS: marking a saved story as unread doesn't stick

### ISSUE THREAD

**Issue by Dejal** [samuelclay/NewsBlur#805] opened 2015-11-03 23:49 UTC
Steps:

1. Go to Saved Stories.
2. Swipe a story in the feed to mark it as unread; it appears as so (with the dot etc).
3. Go back.
4. Return to Saved Stories; it is no longer unread.

**Comment by Dejal** [comment] 2015-11-03 23:58
Experimenting further, it appears to be an issue in the Saved Stories feed, as the story is still shown as unread when viewing in a different feed.  And saving a never-read story (by swiping it without selecting it) still appears as read in Saved Stories.

**Comment by samuelclay** [comment] 2015-11-04 01:02
This is by design. Saved stories can't be marked as unread because they always act as "unreads" in that they are always shown.

**Comment by samuelclay** [comment] 2015-11-04 01:02
We should probably just disabling marking as unread in saved stories, but I wouldn't bother unless it's a trivial change.

**Closed by samuelclay** 2015-11-04 01:02 UTC
Labels: high, iOS

**Comment by Dejal** [comment] 2015-11-04 01:52
I'm not sure that entirely makes sense, since saved stories may be unread or read in another feed, even if they are always listed.  But easy enough to disable marking as read/unread in Saved Stories to avoid unintentional side effects.
