### ISSUE TITLE
iOS: iPad layout issues on v9

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1224] opened 2019-08-08 19:58 UTC
See https://forum.newsblur.com/t/newsblur-9-not-working-on-latest-ipad-pro/7759.

I believe we fixed one of these layout issues but it's possible the others remain.

**Comment by Dejal** [comment] 2019-08-22 22:33
I can't reproduce these with the latest code, in iOS 12 or 13, so were probably fixed by my changes in #1216. I'll leave this issue open for now; let me know if anyone can reproduce them with the 9.1 code (or after that is released). Steps to reproduce would be very helpful.

**Comment by samuelclay** [comment] 2019-08-23 16:58
I've seen it when returning to the iPad app from another app. Try switching to the out-of-app Safari and returning and you should be guaranteed to see it.

**Closed** 2019-08-24 03:15 UTC
Labels: critical, iOS
