### ISSUE TITLE
iOS: iOS 13 support

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1208] opened 2019-06-24 19:32 UTC
Looks like the public beta came out today and NewsBlur crashes on start.

**Comment by kb1ibt** [comment] 2019-06-24 20:26
Duplicate of #1195

**Comment by Dejal** [comment] 2019-06-25 04:13
I've fixed the crash on launch, and another crash when displaying the main menu (with the preferences).

But there are still a bunch of issues. I tested with iOS 13 beta 1, since that's what I had available; some issues may be fixed in subsequent betas. I have only tested on iPhone, not iPad so far.

Known issues:

1. Avoided the startup crash with `sizeToFit` in a `UIBarButtonItem` category. Commenting out fixes that, but may have side-effects.
2. Tapping a folder (section header) in the feeds list doesn't work the second time, as the `viewWillAppear` etc methods aren't getting called for some unknown reason. (Going to individual feeds works fine.)
3. The window background color isn't right (exposed with modal presentation).
4. Nav bar buttons don't appear on Feed Detail view.
5. Segmented controls need some tweaks, especially the theme one.
6. Warning about `UITableView` layout when not in the view hierarchy.

I'll do more work on these issues later. If anyone finds additional issues on iOS 13 betas (that aren't issues on iOS 12), please list them in comments on this issue.

**Comment by Dejal** [comment] 2019-06-28 04:10
Fixed the folder and nav bar buttons issues mentioned above.

Some new issues:

- iPad dashboard header is the wrong color, especially in dark mode.
- Some popover menus are truncated at the top.

The iPhone and iPad apps are usable now; the remaining issues are cosmetic.

Again, please add comments for any noticed issues. And remember that iOS 13 is still a beta, so a moving target. No developer can guarantee support for a beta OS. Use at your own risk!

**Comment by xanthos84** [comment] 2019-06-29 21:08
how to get this build on my ipad?

**Comment by Dejal** [comment] 2019-06-29 23:59
Stay tuned; an update to NewsBlur will be coming soon.

**Comment by samuelclay** [comment] 2019-06-30 21:40
Just released to the App Store seconds ago!

**Comment by samuelclay** [comment] 2019-06-30 21:40
Also, if you want to stay on the bleeding edge, you should be able to open this Xcode project in Xcode and have it compile and install just fine. Is that not the case?

**Comment by Dejal** [comment] 2019-09-21 21:58
This latest commit (165ec98cebdc23a03116b3e8b9abb6602b421864) includes:

- Added a preference to follow the system appearance (light or dark).  Only appears on iOS 13, and defaults on.
- Fixed issues with the preference toggles that would mistakenly reveal other controls when toggling something.
- Fixed cosmetic issues with segmented controls in light and dark themes, especially the theme ones.
- Fixed incorrect appearance of some popovers, causing them to be truncated at the top.
- Fixed the iPad dashboard header colors.
- Fixed the premium manager trying to do UI on a background queue (StoreKit callbacks are not on the main queue). Not an iOS 13 issue, but noticed while testing.
- Preferences was too narrow.
- Fixed white window background (exposed during modal presentation with the new card style).
- Fixed a new warning about table layout when not in the view hierarchy.

I can't find any more issues with iOS 13, but people please add new issues if you spot any. I'll close this issue now. I recommend releasing this update soon, since iOS 13 is rolling out.

**Comment by samuelclay** [comment] 2019-09-22 18:38
Visual crash on Notifications dialog in story titles view.

**Comment by Dejal** [comment] 2019-09-22 23:28
That'd caused by a third-party multi-select segmented control, which makes assumptions about the internal view hierarchy of the segmented control, that are no longer valid. We can't use a segmented control anymore (I've tried to make it work), so I'll change it to use four buttons with highlight colors or images, unless you have any better ideas.

**Comment by nriley** [comment] 2019-09-23 00:55
Or upgrade the third-party control? Looks the latest version is iOS 13-compatible.

https://github.com/yonat/MultiSelectSegmentedControl

In fact, might be worthwhile eventually replacing the unread/focus control with this as the font hasn't matched forever (looks like it's Myriad whereas everything else is Helvetica or San Francisco).

**Comment by Dejal** [comment] 2019-09-23 14:34
Yeah, I considered that, but the control is now completely custom, so wouldn't match the segmented control appearance in iOS 13.  It also has an undocumented dependency on a `SweeterSwift` project. For a simple use like this, I'd rather not have an explosion of dependencies, just to fake something that would probably be better as separate buttons anyway.

**Comment by samuelclay** [comment] 2019-09-23 17:00
Buttons are fine, no need to overthink it. The functionality is what's most important.

**Closed** 2019-09-23 21:53 UTC
Labels: critical, iOS

**Comment by samuelclay** [comment] 2019-09-26 22:19
Can you change the inactive button to have a title color of 0x606060 (instead of 0x000) so it's easier to tell what's active and what's not. I found myself confused.

**Comment by samuelclay** [comment] 2019-09-26 22:23
Another small issue: when tapping on a feed title in the feed list, it doesn't highlight before it disappears.
