### ISSUE TITLE
iOS: feed title is a bit too high

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1850] opened 2024-03-01 23:28 UTC
See this screenshot. The feed title is nudged too high. ![image](https://github.com/samuelclay/NewsBlur/assets/44229/d68840ca-a924-4fb8-8447-07eb61e411a0)

**Comment by Dejal** [comment] 2024-04-30 19:36
This doesn't seem to be an issue in the Catalyst branch?

**Comment by Dejal** [comment] 2024-05-06 22:52
Since this doesn't seem to be an issue in the Catalyst branch, I'm closing this; feel free to re-open if you can reproduce it in the Catalyst branch (preferably along with instructions on how I can do so).

**Closed by Dejal** 2024-05-06 22:52 UTC
Labels: high, iOS

**Comment by samuelclay** [comment] 2024-05-24 01:10
Can you release the catalyst branch (now merged into dejal) to TestFlight for iOS? I want to try it on my phone and can't remember if we setup Xcode Cloud on the dejal branch.

**Comment by Dejal** [comment] 2024-05-24 02:09
Yes, the `NewsBlur for iOS` Xcode Cloud workflow builds the iOS app from the `Dejal` branch. I had deactivated it so it wouldn't trigger when doing Mac builds, but I've just reactivated it and done a TestFlight build.
