### ISSUE TITLE
Android: full screen mode not preserved during rotation

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#701] opened 2015-06-08 03:12 UTC
From https://getsatisfaction.com/newsblur/topics/android-full-screen-mode-does-not-stick:

> Full screen mode is lost when switching from story to text view. 
> 
> Using landscape orientation. 
> 
> app version: 4.2.3 
> android version: 5.0.2 
> device: LGE LG-D410 (MSM8226) 
> memory: normal 
> speed: 31 in 7 and 79 
> premium: yes 
> prefetch: no 
> keepread: no

**Comment by dosiecki** [comment] 2015-06-08 03:21
This is, to a degree, intentional.  We un-trigger immersive mode when the activity changes so that it automatically goes away when context switching or popping back up to the story list or main screen.  

We certainly could try to force the app to stay immersive when rotating by freezing the state along with other parts of the activity.  I'll give this a shot tonight to see if it can be done.

**Comment by manderson23** [comment] 2015-06-08 07:54
So the issue is actually rotation and not switching between story/text as the user said (as this works fine)?

We already have #199 for the various issues related to rotating while reading. I think when I added full screen I didn't think about handling this since there was already an issue to handle it in general.

**Comment by dosiecki** [comment] 2015-06-08 19:30
Yes, should have made that clear: in my testing this is purely a rotation issue and has nothing to do with switching view modes.  I haven't been able to reproduce a loss of immersion by simply switching to or from text mode.

Played around and looks like it is feasible to preserve immersion on rotate.  The animation tends to be a bit odd going out-and-back-in (now I know why most apps that use immersive mode tend to lock rotation!), but I agree this is a better UX.

**Comment by dosiecki** [comment] 2015-06-25 00:02
Fixed in #703.

**Closed by dosiecki** 2015-06-25 00:02 UTC
Labels: android, android-story-detail, medium
