### ISSUE TITLE
iOS: New option for changing height of story titles

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1156] opened 2018-12-20 14:47 UTC
Add this option as a 4 part segmented control in the story titles settings menu. This allows you to increase the height for story titles to get more space for story titles and story content previews. 

4 parts:
 * 2 line title only (this is built but is exposed in a show_content_preview preference)
 * 2 line title + 2 line story content (todays default)
 * 2-4 line title (variable height) + 2-4 line story content (variable height)
 * 2-4 line title (variable height) + 2-6 line story content (variable height)

We'll have to use the new smaller thumbnail to make this work, but it should be top-right positioned, not center-right positioned.

**Comment by samuelclay** [comment] 2019-02-01 00:56
This is great! Can you add a segmented control to the menu on story titles? I think this should be changeable when you're on the view. Widen the popover menu if necessary.

[Title only | S | M | L]
[Title | Short | M | L]
[Title | S | Medium | L]
[Title | S | M | Long]

**Comment by samuelclay** [comment] 2019-02-01 00:57
I don't remember if that's how we do segmented controls. But if it looks bad with changing titles, just use [TITLE ONLY | S | M | L].

**Comment by samuelclay** [comment] 2019-02-01 00:59
Scratch that, make it [TITLE ONLY | 1 | 2 | 3 | 4]

**Comment by Dejal** [comment] 2019-02-01 01:08
Sure, I can do that. I agree that we don't want S | M | L, since those are already used for the font size. Shouldn't change the segment titles with the selection, as that'd make the tap targets move (and would look strange).

**Comment by samuelclay** [comment] 2019-02-07 16:16
On iPad, tapping on the new "title only" control shows the infrequent stories message. Also, there's a visual glitch on the segmented control on the right side.

Also, can you add another segmented control for displaying images: [No Image | Small | Large]

**Comment by samuelclay** [comment] 2019-02-07 16:17
Also, since we're here working on the titles, can we add an HTML decode for the story content preview? Use Outside magazine to test it, as it has many &raquo; html entities.

**Comment by samuelclay** [comment] 2019-02-08 13:59
Also any chance we can make the 2 and 3 options use dynamic heights? I want to avoid titles like this. 

(Ugh I cant upload screenshots on iOS, so imagine or find a story with a single line of title and a single line of content taking up a whole lotta white space)

**Comment by Dejal** [comment] 2019-02-12 22:36
The visual glitch (the segmented control not the same length, I assume you mean) is due to using proportional widths for the titles (the TITLE ONLY segment is wider than the numbers).

With three kinds of small/large options here (preview, image, text), and the struggle to find titles that work, I think it might be time to consider a design tweak. Some suggestions: 

1. A minimal change, prefix each of the segmented controls with a prompt, e.g.

> ORDER: [NEWEST | OLDEST]
> SHOW: [ALL | UNREAD]
> PREVIEW: [NONE | S | M | L]
> IMAGE: [NONE | S | L]
> TEXT: [XS | S | M | L | XL]

2. A variation could be to use images instead of text for the segmented control titles, along with the prompt. Perhaps just for the PREVIEW, IMAGE, and maybe TEXT ones, e.g. 1, 2, 3, or 4 stacked horizontal lines for PREVIEW, small or large image representations for IMAGE, and increasingly large letter A or T for TEXT.

3. Another option could be to replace the segmented controls with disclosure rows that push to a list of options, and show the selected option, like in the preferences (consistency is a good thing):

> ORDER: NEWEST >
> SHOW: UNREAD >
> PREVIEW: MEDIUM >
> IMAGE: SMALL >
> TEXT: MEDIUM >

Should make the corresponding changes to the story menu too. What do you think?

**Comment by Dejal** [comment] 2019-02-13 04:46
I think what I've done is satisfactory, so may not need to tweak the design after all.  So I'll close this. But let me know if you do want to change it to add prompts, or other ideas.

**Comment by samuelclay** [comment] 2019-02-27 18:01
Looks like Large Images and a [2] on story titles is causing overlapping issues.

**Comment by Dejal** [comment] 2019-02-27 21:37
I haven't seen any issues of that with those (or other) settings. Can you show an example, so I can reproduce it?

**Comment by samuelclay** [comment] 2019-03-01 18:26
Happens on Nancy.

![img_761c936bc583-1](https://user-images.githubusercontent.com/44229/53657983-a15a0a80-3c25-11e9-9b87-68533f64d028.jpeg)

**Comment by samuelclay** [comment] 2019-04-13 16:42
Here's another one I see pretty consistently.

https://www.newsblur.com/site/2186/apartment-therapy-saving-the-world-one-room-at-a-time

![IMG_6193](https://user-images.githubusercontent.com/44229/56082677-9a5c1580-5de9-11e9-8cf7-4ba965d564b5.PNG)

**Comment by samuelclay** [comment] 2019-05-10 01:59
I'm still getting this bug on a few titles, I think always with an image. Check the NYT feed. If you like, use the `android_speed` account (password is newsblur) and you should be able to see a huge variety in the river.

**Closed** 2019-05-17 02:57 UTC
Labels: high, iOS
