### ISSUE TITLE
iOS: Images fail to load

### ISSUE THREAD

**Issue by nriley** [samuelclay/NewsBlur#1002] opened 2017-03-17 19:34 UTC
On a regular basis, stories whose contents are exclusively or mostly images don't load their images.  This happens most commonly with Web comics but also with sites like Flickr.  This never happens on the Web.  This issue has been happening for months to perhaps even years.  It is not consistent within a single feed — sometimes an image will load, sometimes it won't.  The same thing affects the images in the article list.  I have had trouble reproducing this with a debugger attached, but figured I might as well post a few examples here from today:

![img_2464](https://cloud.githubusercontent.com/assets/68303/24059801/bb8b8690-0b26-11e7-86c3-093c65b640a0.PNG)

![img_2465](https://cloud.githubusercontent.com/assets/68303/24059809/c3aa798a-0b26-11e7-9555-227a3942c2ef.PNG)

You can see below that 4 recent xkcd comics loaded fine, and 2 didn't.

![img_2466](https://cloud.githubusercontent.com/assets/68303/24059875/133aad76-0b27-11e7-9e3d-2f7b92e60247.PNG)

**Comment by samuelclay** [comment] 2017-03-17 20:07
Do you have Offline images enabled? We rewrite image URLs when that preference is turned on, choosing to use the local copy instead of the remote copy. It's possible the local copy is not fully downloaded but we use it anyhow.

**Comment by nriley** [comment] 2017-03-17 20:52
(Whoops, didn't mean to close it!) Yes, I have offline images enabled. I tried turning off and deleting offline stories and this indeed causes the images to appear.

**Comment by Dejal** [comment] 2019-01-31 02:47
Is this still occurring? I can't reproduce it, but that doesn't prove anything.

**Comment by Dejal** [comment] 2019-08-24 03:20
Closing this; please re-open if it still occurs for you (and provide steps to reproduce).

**Closed by Dejal** 2019-08-24 03:20 UTC
Labels: iOS
