### ISSUE TITLE
ipados 13 beta 1/2 - app not working

### ISSUE THREAD

**Issue by xanthos84** [samuelclay/NewsBlur#1207] opened 2019-06-19 20:20 UTC
hi 
do you plan to update the app so it will run under ios 13 b1/2?
thank you

**Comment by kb1ibt** [comment] 2019-06-24 20:25
Duplicate of #1195

**Comment by samuelclay** [comment] 2019-06-24 20:32
Let's go with #1195

**Closed by samuelclay** 2019-06-24 20:32 UTC
