### ISSUE TITLE
iOS: Add private save to sharing extensions

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1515] opened 2021-07-12 18:20 UTC
The sharing extension right now only supports public shares. Let's add private saves as well, including story tags. We launched this on the web only recently but it's because a necessary feature.

https://blog.newsblur.com/2020/07/17/highlight-passages-and-add-private-notes-on-saved/

**Comment by Dejal** [comment] 2021-07-22 04:16
I have rewritten the share extension to support this, since the basic old one couldn't be customized sufficiently.

It all works well, except the saved story doesn't show up in NewsBlur. The `POST` request is accepted, so I'm not sure what the issue is.

Can you please try saving a story via the share extension, and look at the server side to see why it isn't working?

It is using the `api/save_story` endpoint, which looking at the server code (as much as I can understand it) seems to be correct, but perhaps a parameter is wrong; I don't see an issue.

**Comment by samuelclay** [comment] 2021-08-17 22:49
Looks like I could share fine with it. I wonder if something has changed in the past month, since I've been doing a lot of maintenance. 

My saved story tags did not load though. And I couldn't save without a tag.

**Comment by garymh** [comment] 2021-10-03 20:18
I can't seem to use it as well. Even with a tag 😔

**Comment by samuelclay** [comment] 2022-01-07 21:49
I'd like to add the count to the saved story tags as well, to better match the web. It's always nice to see which of my tags have high counts and which have low, as it helps me organize.

**Comment by samuelclay** [comment] 2022-01-07 22:02
Looks like the request doesn't even hit the server.

**Comment by Dejal** [comment] 2022-03-10 05:05
I've added the tag count, and tested it; seems to work fine now. So I'll close this.

**Closed by Dejal** 2022-03-10 05:05 UTC
Labels: backend, high, iOS

**Comment by samuelclay** [comment] 2022-03-10 21:08
This is such a nice experience now! All three tabs are great. Makes me want to hire a designer to give it the fit and finish it now deserves.

**Comment by samuelclay** [comment] 2022-03-10 21:09
Wouldn't it be cool if the sharing extension showed a preview of the story? The web does this, but it uses a javascript readability library, which we could use just as well here.
