### ISSUE TITLE
App crashes immediately after accepting Share story

### ISSUE THREAD

**Issue by onos1** [samuelclay/NewsBlur#1092] opened 2018-03-20 10:58 UTC
#### Expected behavior
Using the newsblur app,  after sharing an interesting article I expect to continue with various activities in the app like read more stories or seeing success of story shared successfully then I continue.

#### Actual behavior
After reading a specific content or any content, once you share the news, the app crashes.

#### How to reproduce
Download the newsblur app [here](https://f-droid.org/repository/browse/?fdid=com.newsblur)
- Register with your correct details 
- after registration, click on global shared stories
- click three dot at top right corner 
- select share story
- click share (I didn't add a comment)
- app crashes 

* mobile : Infinix note 4
* Operating system: android 7.0
* version : 7.0.3
#### Recording Of The Bug
Using my video screen recorder, here is a video to reproduce the bug 
https://youtu.be/R-mh7yJge40
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@onos/app-crashes-immediately-after-accepting-share-story">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dosiecki** [comment] 2018-03-20 11:03
Thanks for the report. Did you tap the "Send Feedback" option that was offered? That is the most reliable and efficient way to ensure we can get our hands on the information needed to solve mysteries such as this.

**Comment by dosiecki** [comment] 2018-03-23 04:20
I just pushed a quick fix for this so it will fail more gracefully, but I just re-watched your video and saw that something even more strange is going on, as it appears that you are logged in but have no username? (as seen on the main screen of the app in the top-left corner)

Could you please start the app (no need to make it crash), and use the "Send app feedback (v...) -> Email a bug report)" option from the main menu?

**Comment by dosiecki** [comment] 2018-03-23 08:18
> Am logged in...it doesn't show when checking global news. Only on home page

It should always show on the feed list (the first/main page in the app), but not after you tap into a feed or folder.  Did you do anything since recording that video such as logging out and back in or clearing app data?

Please do use the "Send app feedback (v...) -> Email a bug report)" option, and *after* having sent the email, you can try logging out and then back in, which may help until we can track down root cause.

**Comment by onos1** [comment] 2018-03-23 10:38
Na....

**Comment by dosiecki** [comment] 2018-03-23 23:28
Without any additional info it will be difficult to track down an original cause.  Went ahead and added some logic to request a new login cycle if for some reason login info gets lost or corrupted.

**Closed by dosiecki** 2018-03-23 23:28 UTC
Labels: android, android-story-list
