### ISSUE TITLE
iPad: Next story overlaps on interactive gesture between views

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1654] opened 2022-03-21 18:17 UTC
See the video:

https://user-images.githubusercontent.com/44229/159338152-02c59761-831c-4bae-8321-41e1635b8be2.MP4

**Comment by Dejal** [comment] 2022-04-05 02:30
I can't reproduce this. It might have been fixed by a related recent layout change, or might be sporadic. Let me know whether or not you can repro it with the Dejal branch.

**Comment by Dejal** [comment] 2022-04-05 15:38
Here's a hint: when I send an invoice, I'm done for the work block. :)

I'll probably do some more tonight and/or tomorrow, then you'll be good to go. Again, watch for the invoice as a signal.

Using TestFlight is probably a good idea, though with bug fixes isn't essential. Testing in production is good enough for the website, so good enough for the app!

**Comment by Dejal** [comment] 2022-04-06 23:22
I don't have a 10.5" iPad simulator, but using the 11-inch iPad Pro simulator (which should be similar), it doesn't misbehave in either two or three column layout. Can you repro it using the Dejal branch?

https://user-images.githubusercontent.com/1318849/162088344-d0bf1ccc-a2ff-423a-b210-553d3dd791c9.mp4

**Closed** 2023-07-21 16:14 UTC
Labels: high, iOS, blocked
