### ISSUE TITLE
Dialogs disappear on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [samuelclay/NewsBlur#972] opened 2016-12-11 11:27 UTC
When i perform these sequences of events, the dialog on screen disappears:

Sequence 1:
1. Click on story item in list
2. Click on ... to open action overflow menu
3. Click on Adjust Text Size
4. Orientation Change

Sequences 2-9:
1. Click on Preferences
2. Click on:
a. Download Using
b. Story Order
c. Read Filter
d. Confirm Mark all Read
e. Volume Key Navigation
f. Theme
g. Rightward swipe
h. Leftward swipe
3. Orientation Change

**Comment by samuelclay** [comment] 2016-12-30 00:16
Sweet, a huge thank you for writing up these test cases. #973 #974 #975 #976 

I'll let you know now that these are quite difficult to fix. We got the biggest orientation bugs fixed only in the most recent big release, and that was because I brought in the big guns to squash rotation while reading or watching a video (thank you again @Dejal). 

Hey @dejal, what do you make of these? Something we could fix or are these lost causes from the dust bin of 2011-era code.

**Comment by Dejal** [comment] 2016-12-30 02:00
Any issue can be fixed, given enough time.  I agree that all of these are curly ones; a lot of things change on rotation, which makes it hard to preserve state.  I'd be happy to tackle them if you like, but you might want to set a time limit (and so I'd do as many as I can in that time).

**Comment by samuelclay** [comment] 2016-12-31 00:16
Yeah I don't feel a pressing need to go over these, but if you can take an hour or two to get a feel for the depth of the problem and chart out possible solutions, I'd be fine with that. But I've personally sunk way too much time into fixing these sorts of bugs.

**Comment by Dejal** [comment] 2016-12-31 00:42
Okay, will do.

**Comment by Dejal** [comment] 2017-01-01 22:17
@reverse-unina what kind of device are you using for this?  I can't reproduce rotation issues with the Preferences on either iPhone or iPad.  There also isn't a "..." menu as far as I'm aware, so I'm wondering if you're using an Android device?

**Comment by reverse-unina** [comment] 2017-01-02 00:51
Yes, I am using a set of real and virtual android devices.
The ... Is the action overflow menu in the right top corner

**Comment by dosiecki** [comment] 2017-01-02 23:43
In general, it is perfectly normal for context menus to disapear on device rotation.  Pop up any '...' menu or a context menu in an app like Chrome or the Play Store and rotate your device: the menu will collapse.  While I don't believe this behaviour is necessarily prescribed, neither is it even remotely uncommon.

Stepping back, though, what is the root concern here?  Is there some situation where you are losing entered state or data on rotation?  That I would consider worth looking into.

**Comment by reverse-unina** [comment] 2017-01-03 10:37
Yes, this kind of issue is very common but still undesired and not normal. It violates the Android guidelines and negatively affects the user experience, e.g. why should we repeat a click or a gesture?
Google Docs fixed one of these failures in the latest version.
In Youtube if I perform this sequence of events, the contextual menu does not disappear:

1. Click on Search icon
2. Enter text
3. Long click on a result item
4. Orientation Change

Other open source applications on F-Droid, e.g. Transistor also show a correct behaviour (persistence of the menu).

We know that other apps show this failure. Most of them, like Google Docs, corrected this behavior.

**Comment by dosiecki** [comment] 2017-01-03 10:59
Please see my detailed notes on each issue you filed.  If you are losing state such as entering text, please be specific as to what state you lost in which activity or dialogue.  (Please also confirm it is not one of our known issues around state loss on context switch, #199, #980, etc)

When it comes to things like context menus disappearing, though, I can pretty much guarantee you that we will keep relying upon devices' platform behaviour.  Attempting to fix a default behaviour like this on a per-app basis is ambitious beyond our resources.

**Closed by dosiecki** 2017-01-03 10:59 UTC
Labels: android

**Comment by samuelclay** [comment] 2017-01-03 20:14
Sorry, this was my fault in miscategorization. I should've realized this was Android from the top description.
