### ISSUE TITLE
iOS: Swiping back from original story view breaks all navigation

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#876] opened 2016-02-08 17:53 UTC
Open any story and either double-tap or tap the original story button. If you swipe back (not just hit the Done button) from the SafariViewController, all navigation is broken. You can't do anything after that.

**Comment by Dejal** [comment] 2016-02-08 22:26
iPhone or iPad?  I can't reproduce this on either.  Can you provide any more details on how to reproduce and what happens?

**Comment by samuelclay** [comment] 2016-02-08 22:43
iPhone. I was able to reproduce it regularly. I was in a dark theme. And bingo ... you have to be in a dark theme.

**Comment by Dejal** [comment] 2016-02-09 00:53
It does seem more reproducible in a dark theme, though I don't think that is the cause.  A symptom of the issue is that the `-[StoryPageControl viewDidAppear:]` method isn't getting called.  Experiments show that if you swipe slowly (or tap Done), it works properly, but if you swipe quickly, it fails.

This appears to be a [known bug in iOS 9.2](https://forums.developer.apple.com/thread/29048).

I've tried manually calling the `-viewDidAppear:` method, or manually dismissing the `SFSafariViewController`, but nothing helped.

**Comment by samuelclay** [comment] 2016-02-09 01:07
Well, crap. This is kind of a blocker. I wonder if this happens in the shipping app.

**Comment by Dejal** [comment] 2016-02-09 01:44
Dunno.  I've posted to that thread, and filed a Radar (#24560676).  If I think of anything else to try, I'll give it a go.

**Comment by nriley** [comment] 2016-03-05 14:45
I can't seem to reproduce this bug - everything works fine after swiping back from in-app Safari on my iPhone 6s and iPad Air with 9.2.1 and iPhone 5s with 9.3b5. Maybe I'm incapable of swiping fast enough. There is a workaround to disable swiping in the thread you linked to now, though.

**Comment by Dejal** [comment] 2016-03-05 18:22
It is a bit sporadic, and seems to occur more on dark themes for some reason.

I offered to implement that workaround, but Sam said that since it's an iOS bug, it should get fixed in due course.  So I think we'll live with it, and hope not too many people encounter it.

**Closed** 2018-07-14 14:59 UTC
Labels: critical, iOS
