### ISSUE TITLE
Android v1.2: Rotation closes article

### ISSUE THREAD

**Issue by Linecutterx** [samuelclay/NewsBlur#1603] opened 2022-01-27 07:23 UTC
In 11.1.1 (the latest one!) there is no problem, but something in the change to 1.2 (via Fdroid) has introduced an issue.

If I open a web comic strip article from a feed & then rotate the phone (portrait->landscape) then the article closes & I end up back at the feed. (Which is annoying because I haven't read the article yet!) Something to do with destroying the view in order to rotate, & the checking added for premium use? (I have a self hosted custom domain, which might be relevant if that's the case)

**Comment by yaomtc** [comment] 2022-01-31 20:30
For me, if I tap on a story, open the link in my browser, rotate my screen, then hit Back after I'm done to return to Newsblur... Newsblur is now an unresponsive white screen until I swipe Newsblur out of the recent apps and restart it.

If I rotate the screen back to portrait before leaving my browser, this issue does not occur.

I am using the latest Newsblur from F-Droid (11.2) on a Pixel 4a.

**Comment by daradib** [comment] 2022-02-04 01:23
I think this may have been fixed in 11.2.2 (or 11.2.1). I experienced similar unresponsiveness/crashes on 11.2 (F-Droid) but am unable to reproduce any issues with rotation on 11.2.2 (Play). Can the changes for 11.2.2 be pushed to this repo so F-Droid can build the updated version?

**Comment by sictiru** [comment] 2022-02-09 06:19
Tried to replicate with 11.2.1 without success. 
@Linecutterx @yaomtc Could you give 11.2.2 from Play Store a try?

**Comment by Linecutterx** [comment] 2022-02-09 07:30
Agreed. Play Store 1.2.2 doesn't have the rotation issue.
Close this please. :)

**Closed** 2022-02-09 07:31 UTC
Labels: critical, android
