### ISSUE TITLE
iOS:  After viewing All Stories, going to Saved Stories on iPad will get stuck in "syncing" loop

### ISSUE THREAD

**Issue by jangellx** [samuelclay/NewsBlur#800] opened 2015-11-02 18:26 UTC
iOS 9.1, iPad Air 2.  This one doesn't always happen, and I wasn't able to reproduce it at the time I submit this, but I have seen it with the latest beta.

These are the rough steps:
- Launch NewsBlur
- Go to All Stories
- Read your stories, until the queue is empty (I wonder if you need to go through enough stories that it has to load another batch from the server?)
- Go back to the main page
- Go to Saved Stories.  Often the "Syncing" popover thing will appear, fading in and out, like it's stuck in a loop.  The only way to get to Saved Stories is to kill the app and relaunch.

I'll post a screenshot next time I see it, and see if I can get more reproducible steps.  Thanks.

**Comment by samuelclay** [comment] 2015-11-02 19:42
Thanks for posting this1

**Comment by Dejal** [comment] 2015-11-02 21:16
I can't reproduce this, though not too surprising if sporadic or dependent on some data state.

**Comment by jangellx** [comment] 2015-11-02 21:18
I'll see if I can get better steps.  Next time it gets in the loop I'll see if I can plug it into my Mac and record a short video of what I'm seeing.  I'm not sure it'll be super helpful, since it won't tell you how it got into that state, but maybe you'll see something I don't.

**Comment by jangellx** [comment] 2015-11-03 22:03
Turns out "syncing" was the right word -- it's actually "Finding Story...".  Here's a screenshot of where I managed to break the app in the "All Stories" view.  This is a bit different than normal, since I don't usually see the "Finding text" bit in the right pane.  In this both also stayed on solidly, and didn't fade in and out.

![img_0050](https://cloud.githubusercontent.com/assets/3717537/10923052/b7e9db72-824c-11e5-8c30-3ac672a0b761.jpg)

I'll continue looking for better steps and a more accurate repro case.

**Comment by Dejal** [comment] 2016-01-30 00:35
I still can't reproduce this one.  Does it still occur?  Any more clues?

**Comment by jangellx** [comment] 2016-01-30 20:53
I haven't seen this issue in a while now.  I think it magically got fixed in a prior update, and I just forget about it as everything was working as expected now.

Sorry for the trouble.  I'll try to check back on bug reports if I haven't repro'ed them in some time.  Thanks

**Comment by Dejal** [comment] 2016-01-30 21:56
No problem; I'm glad it seems to be fixed.  I'll close this now, but if it does occur again, please let us know.  We appreciate your help reporting issues.

**Closed by Dejal** 2016-01-30 21:56 UTC
Labels: high, iOS
