### ISSUE TITLE
iOS: Premium Archive subscription

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/NewsBlur#1695] opened 2022-06-01 18:43 UTC
We have a new subscription tier launching soon. It's on beta.newsblur.com. Here's the extra text we need to add (found in: https://github.com/samuelclay/NewsBlur/blob/e09c97ef6f60d018eb3ab040203ebfe24cf7c367/media/js/newsblur/reader/reader_feedchooser.js#L184-L217) 

<img width="1483" alt="Screen Shot 2022-06-01 at 2 43 18 PM" src="https://user-images.githubusercontent.com/44229/171479030-112b5a65-0547-472c-87f7-47addcf91fc0.png">

**Comment by Dejal** [comment] 2022-06-21 02:16
FYI, the icons don't work in dark mode (on the website):

<img width="619" alt="Screen Shot 2022-06-20 at 20 14 24" src="https://user-images.githubusercontent.com/1318849/174702143-64499fc7-1f36-4c66-88ad-3edb6b52e24a.png">

**Comment by samuelclay** [comment] 2022-06-21 14:34
Fixed, thanks!
<img width="560" alt="Screen Shot 2022-06-21 at 10 34 30 AM" src="https://user-images.githubusercontent.com/44229/174826184-04a6a6f7-bf91-44e2-9845-e4b7a37a51b7.png">

**Comment by Dejal** [comment] 2022-06-22 02:23
I don't suppose you could list the icon names for me, so I don't have to try to map the CSS identifiers to images? If too hard, I can troll for them.

**Comment by Dejal** [comment] 2022-06-22 02:39
Also, at some point you'll need to add a new subscription in [App Store Connect](https://appstoreconnect.apple.com/apps/463981119/appstore/subscription-groups/20421002), and let me know the identifier. For reference, the identifier of the current subscription is `newsblur_premium_auto_renew_36`. I'll use `newsblur_premium_archive` as the identifier in the app, but it can be changed if you choose something else in App Store Connect.

No need to do anything yet.

**Comment by samuelclay** [comment] 2022-06-22 20:26
Ok, newsblur_premium_archive is in there, although I need a screenshot to get it approved first

**Comment by samuelclay** [comment] 2022-06-22 20:28
And all of the new icons are under `/media/img/icons/nouns/`. They should be self explanatory, but you may have to cross reference with reader.css or using a web inspector.

**Comment by Dejal** [comment] 2022-06-23 01:38
Hmm. I can't find the icons. Using the web inspector, it says the path is https://beta.newsblur.com/media/embed/icons/icons8/, but there isn't an `icons8` folder in the repo. There isn't a `nouns` folder in the `/media/img/icons/` folder, either. Are they not committed, or something? Can you point to them in the repo?

**Comment by Dejal** [comment] 2022-06-23 03:36
I've finished this, other than updating the icons. I modeled it after the web edition, with iOS-specific tweaks.

Here's a screen recording, showing the app with a Premium subscription but not a Premium Archive one. Notice the "English" title that needs fixing in App Store Connect.

https://user-images.githubusercontent.com/1318849/175202730-9c7c889e-ad0a-4c67-812c-1c32576ded54.mp4

**Comment by Dejal** [comment] 2022-06-24 02:32
Done. Here are a couple of screenshots for the IAP approval.

![Simulator Screen Shot - iPhone 13 Pro - 2022-06-23 at 20 30 06](https://user-images.githubusercontent.com/1318849/175450399-fcb41f72-65a4-4b82-94f3-45a16b84ce8e.png)
![Simulator Screen Shot - iPhone 13 Pro - 2022-06-23 at 20 30 02](https://user-images.githubusercontent.com/1318849/175450419-e9e4fea5-5b71-4424-a924-f9d9667cded1.png)

**Closed by Dejal** 2022-06-24 02:32 UTC
Labels: high, iOS

**Comment by samuelclay** [comment] 2022-06-28 16:50
Looking good, let's work through some notes:

 * I have `is_archive` set to True but I still saw the "Upgrade to Archive" menu item. It should have read "Premium Subscription" for me.
 * Let's remove the confetti. It kept turning on and off for me and is no longer appropriate for the dialog.
 * On iPad, the Terms of Use button is cut off
 * Let's move the Manage Subscription button to the bottom of the active premium section. We'll soon enough have a third and fourth premium, so we'll need to manage how we expand this list.

**Comment by Dejal** [comment] 2022-07-06 03:00
I can't reproduce your "Upgrade to Archive"; if I log in as you, it successfully shows "Premium Archive". Maybe it hadn't finished loading the profile?
